name: VantiUtilities
description: Utilities for Vanti Server
author: Aubli
version: 0.0.1

main: me.Aubli.VantiUtilities.VantiUtilities

commands:
    rank:
        description: rank command
        usage: /<command> <player> <rank>