name: VantiUtilities
description: Utilities for Vanti Server
author: Aubli
depend: [Vault]
version: 0.9

main: me.Aubli.VantiUtilities.VantiUtilities

commands:
    rank:
        description: Rank command
        usage: /<command> <player> <rank>
    vanti:
        description: Vanti commands
        usage: /<command> reload
    nightvision:
        description: Toggles night vision
        usage: |
               /<command>
               /<command> <player>
        aliases: [nv]