name: VantiUtilities
description: Utilities for Vanti Server
author: Aubli
version: 0.0.1

main: me.Aubli.VantiUtilities.VantiUtilities

commands:
    rank:
        description: Rank command
        usage: /<command> <player> <rank>
    vanti:
        description: Vanti commands
        usage: /<command> reload